development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:ed47430b3f8fbbd606f02003f03b549a@pike.redistogo.com:11118/
  channel_prefix: one_bit_messenger_production
