development:
  adapter: redis
  url: <%= Rails.application.credentials[Rails.env.to_sym][:redis_url] %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= Rails.application.credentials[Rails.env.to_sym][:redis_url] %>
  channel_prefix: one_bit_messenger_production
