test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials[Rails.env.to_sym][:access_key_id] %>
  secret_access_key: <%= Rails.application.credentials[Rails.env.to_sym][:secret_access_key] %>
  region: <%= Rails.application.credentials[Rails.env.to_sym][:region] %>
  bucket: <%= Rails.application.credentials[Rails.env.to_sym][:bucket] %>
